// Generated by CoffeeScript 1.10.0
var helperFn;

helperFn = function(window, $) {
  var gConfig;
  gConfig = window.gConfig;
  return window.helper = {
    getRandomInt: function(min, max) {
      if (min == null) {
        min = 1;
      }
      if (max == null) {
        max = 10;
      }
      min = Math.ceil(min);
      max = Math.floor(max);
      return Math.floor(Math.random() * (max - min)) + min;
    },
    sendMessage: function(config) {
      var dfd;
      dfd = $.Deferred();
      chrome.runtime.sendMessage(config, function(response) {
        return dfd.resolve(response);
      });
      return dfd;
    },
    getJson: function(url, data) {
      return this.sendMessage({
        url: url,
        data: data,
        type: 'getJson'
      });
    },
    postJson: function(url, data) {
      return this.sendMessage({
        url: url,
        data: data,
        type: 'postJson'
      });
    }
  };
};

helperFn(this, $);
