// Generated by CoffeeScript 1.10.0
var loaderFn;

loaderFn = function(window, $) {
  var injectHtml;
  injectHtml = function(file) {
    var url;
    url = chrome.extension.getURL(file);
    return $.get(url).then(function(data) {
      console.log("[loader] inject " + file + " to body.");
      return $(data).appendTo('body');
    });
  };
  return window.loader = {
    loadTemplate: function() {
      return injectHtml('template/header.html');
    }
  };
};

loaderFn(this, $);
