// Generated by CoffeeScript 1.10.0
chrome.runtime.sendMessage({
  type: 'setting'
}, function(setting) {
  jQuery(document).ready(function() {
    return jQuery('<div class="fairydict-tooltip"></div>').appendTo('body');
  });
  jQuery(document).mousemove(function(e) {
    var mousex, mousey;
    mousex = e.pageX + 20;
    mousey = e.pageY + 10;
    return jQuery('.fairydict-tooltip').css({
      top: mousey,
      left: mousex
    });
  });
  jQuery(document).bind('keyup', function(event) {
    if (utils.checkEventKey(event, setting.openSK1, setting.openSK2, setting.openKey)) {
      return chrome.runtime.sendMessage({
        type: 'look up',
        means: 'keyboard',
        text: window.getSelection().toString()
      });
    }
  });
  return jQuery(document).mouseup(function(event) {
    var including, selObj;
    selObj = window.getSelection();
    if (!selObj.toString()) {
      jQuery('.fairydict-tooltip').fadeOut();
      return;
    }
    including = jQuery(event.target).has(selObj.focusNode).length || jQuery(event.target).is(selObj.focusNode);
    if (event.which === 1 && including) {
      if (setting.enablePlainLookup) {
        chrome.runtime.sendMessage({
          type: 'look up pain',
          means: 'mouse',
          text: window.getSelection().toString()
        }, function(res) {
          var definition;
          if (res.defs) {
            definition = res.defs.reduce((function(n, m) {
              if (n) {
                n += '<br/>';
              }
              n += m.pos + ' ' + m.def;
              return n;
            }), '');
            console.log("[FairyDict] plain definition: ", definition);
            return jQuery('.fairydict-tooltip').html(definition).fadeIn('slow');
          }
        });
      }
      if (!setting.enableMouseSK1 || (setting.mouseSK1 && utils.checkEventKey(event, setting.mouseSK1))) {
        return chrome.runtime.sendMessage({
          type: 'look up',
          means: 'mouse',
          text: window.getSelection().toString()
        });
      }
    }
  });
});

chrome.runtime.sendMessage({
  type: 'injected',
  url: location.href
});
