// Generated by CoffeeScript 1.10.0
var dictApp;

dictApp = angular.module('fairyDictApp', ['ngRoute', 'ui.bootstrap', 'ngSanitize']);

dictApp.controller('dictCtrl', function($scope) {
  var ref;
  console.log("[dictCtrl] init");
  $scope.initial = true;
  $scope.querying = false;
  $scope.queryResult = null;
  $scope.query = function() {
    console.log("[dictCtrl] query `" + $scope.word + "` from " + $scope.dictionary);
    $scope.initial = false;
    $scope.querying = true;
    return chrome.runtime.sendMessage({
      type: 'query',
      text: $scope.word,
      dictionary: $scope.dictionary
    });
  };
  if ((ref = chrome.runtime.onMessage) != null) {
    ref.addListener(function(request, sender, sendResponse) {
      if (request.type === 'querying') {
        $scope.initial = false;
        return $scope.querying = true;
      } else if (request.type === 'queryResult') {
        $scope.querying = false;
        return $scope.queryResult = request.data;
      }
    });
  }
});
