// Generated by CoffeeScript 2.4.1
var dictApp;

dictApp = angular.module('fairyDictApp', ['ngRoute', 'ui.bootstrap', 'ngSanitize']);

dictApp.controller('optionCtrl', function($scope, $sce) {
  var code;
  console.log("[optionCtrl] init");
  $scope.allSK = ['', 'Ctrl', 'Shift', 'Alt', 'Meta'];
  $scope.allLetters = (function() {
    var i, ref, ref1, results;
    results = [];
    for (code = i = ref = 'A'.charCodeAt(0), ref1 = 'Z'.charCodeAt(0); (ref <= ref1 ? i <= ref1 : i >= ref1); code = ref <= ref1 ? ++i : --i) {
      results.push(String.fromCharCode(code));
    }
    return results;
  })();
  $scope.extraKeys = Object.keys(window.utils.extraKeyMap);
  $scope.allKeys = $scope.allLetters.concat($scope.extraKeys);
  $scope.allPositions = ['topLeft', 'topCenter', 'topRight', 'middleLeft', 'middleCenter', 'middleRight', 'bottomLeft', 'bottomCenter', 'bottomRight'];
  $scope.changeKey = function(value, key) {
    $scope.setting[key] = value;
    return chrome.runtime.sendMessage({
      type: 'save setting',
      key: key,
      value: value
    });
  };
  return chrome.runtime.sendMessage({
    type: 'setting'
  }, function(config) {
    $scope.setting = config;
    $scope.$apply();
    if (!config.upgradeNotice) {
      setTimeout(function() {
        return alert("疫情期间在家重构了 FairyDict, 此扩展的升级版 Dictionaries 已发布， 添加了管理单词表和词典列表的功能， 甚至还支持日语查询， 欢迎去下载使用 Dictionaries. FairyDict 将不再更新!");
      }, 100);
      return chrome.runtime.sendMessage({
        type: 'save setting',
        key: 'upgradeNotice',
        value: true
      });
    }
  });
});
