// Generated by CoffeeScript 1.10.0
define(["jquery", "utils", "background/setting", "background/dict.js", "background/storage"], function($, utils, setting, dict, storage) {
  var defaultWindowUrl, dictInitedDfd, dictWindowManager, injectContentDfd, updateWindowDfd;
  console.log("[dictwindow] init");
  defaultWindowUrl = 'http://blog.riverrun.xyz/fairydict.html';
  updateWindowDfd = null;
  injectContentDfd = null;
  dictInitedDfd = null;
  dictWindowManager = {
    w: null,
    tid: null,
    lastUrl: null,
    defaultWidth: 600,
    defaultHeight: 700,
    open: function() {
      var dfd, left, top, url;
      dfd = $.Deferred();
      left = (screen.width / 2) - (dictWindowManager.defaultWidth / 2);
      top = (screen.height / 2) - (dictWindowManager.defaultHeight / 2);
      url = 'http://blog.riverrun.xyz/fairydict.html';
      if (!this.w) {
        this.beforeUpdateUrl();
        chrome.windows.create({
          url: defaultWindowUrl,
          type: 'popup',
          width: dictWindowManager.defaultWidth,
          height: dictWindowManager.defaultHeight,
          left: left,
          top: top
        }, (function(_this) {
          return function(win) {
            _this.w = win;
            _this.tid = _this.w.tabs[0].id;
            _this.lastUrl = defaultWindowUrl;
            return dfd.resolve();
          };
        })(this));
      } else {
        chrome.windows.update(dictWindowManager.w.id, {
          focused: true
        });
        dfd.resolve();
      }
      return dfd;
    },
    sendMessage: function(msg) {
      if (this.tid) {
        return chrome.tabs.sendMessage(this.tid, msg);
      }
    },
    lookup: function(text) {
      var dictName;
      dictName = setting.getValue('dictionary');
      return this.open().done((function(_this) {
        return function() {
          if (text) {
            _this.sendMessage({
              type: 'querying',
              text: text
            });
            return _this.queryDict(text, dictName);
          }
        };
      })(this));
    },
    queryDict: function(text, dictName, inHistory) {
      if (!inHistory) {
        this.sendMessage({
          type: 'history',
          history: storage.history
        });
      }
      return dict.query(text, dictName).then((function(_this) {
        return function(res) {
          var d1, item;
          if (text.split(/\s+/).length <= 5 && !inHistory) {
            storage.addHistory(text);
          }
          console.log("[dictwindow] query " + text + " from " + dictName);
          item = storage.isInHistory(text);
          d1 = _this.updateUrl(res.windowUrl || defaultWindowUrl);
          return $.when(d1, updateWindowDfd, dictInitedDfd).then(function() {
            console.log("[dictwindow] send query result");
            return _this.sendMessage({
              type: 'queryResult',
              result: res,
              text: text,
              inHistory: inHistory,
              rating: item != null ? item[text] : void 0
            });
          });
        };
      })(this));
    },
    injectResources: function() {
      var inject, res, scripts, styles;
      styles = ["css/bootstrap.css", "bower_components/angular-ui/build/angular-ui.css", "bower_components/angular-bootstrap/ui-bootstrap-csp.css", "css/font-awesome.css", "css/dictheader.css"];
      scripts = ['bower_components/jquery/dist/jquery.js', 'bower_components/underscore/underscore.js', "bower_components/angular/angular.js", "bower_components/angular-ui/build/angular-ui.js", "bower_components/angular-sanitize/angular-sanitize.js", "bower_components/angular-bootstrap/ui-bootstrap.js", "bower_components/less/dist/less.js", "utils.js", "js/starrr.js", "loader.js", "dict.js"];
      inject = (function(_this) {
        return function(t, files, index) {
          var dfd, file;
          if (files == null) {
            files = [];
          }
          if (index == null) {
            index = 0;
          }
          dfd = $.Deferred();
          file = files[index];
          if (file) {
            console.log("[dictwindow] inject " + file);
            chrome.tabs[t](_this.tid, {
              file: file
            }, function() {
              return inject(t, files, index + 1).then(function() {
                return dfd.resolve();
              });
            });
          } else {
            dfd.resolve();
          }
          return dfd;
        };
      })(this);
      res = dict.getDictResources(setting.getValue('dictionary'));
      return inject('insertCSS', res != null ? res.styles : void 0).then((function(_this) {
        return function() {
          return inject('insertCSS', styles).then(function() {
            return inject('executeScript', scripts).then(function() {
              return inject('executeScript', res != null ? res.scripts : void 0);
            });
          });
        };
      })(this));
    },
    updateUrl: function(url) {
      var outDfd;
      outDfd = $.Deferred();
      if (url && this.lastUrl !== url) {
        console.log("[dictwindow] update url: " + url);
        this.lastUrl = url;
        this.beforeUpdateUrl().then((function(_this) {
          return function() {
            console.log("[dictwindow] updated url: " + url);
            return outDfd.resolve(true);
          };
        })(this));
        chrome.tabs.update(this.tid, {
          url: url,
          active: true
        });
        return outDfd;
      } else {
        return outDfd.resolve(false);
      }
    },
    beforeUpdateUrl: function() {
      injectContentDfd = $.Deferred((function(_this) {
        return function(dfd) {
          return dfd.then(function() {
            return _this.injectResources().then(function() {
              return updateWindowDfd.resolve();
            });
          });
        };
      })(this));
      dictInitedDfd = $.Deferred();
      updateWindowDfd = $.Deferred();
      return updateWindowDfd;
    },
    onContentInjected: function(url) {
      if (url === this.lastUrl) {
        console.log("[dictwindow] manifest's content scripts injected from url: " + url);
        return injectContentDfd != null ? injectContentDfd.resolve() : void 0;
      }
    },
    onDictInited: function() {
      console.log("[dictwindow] dict inited");
      if (dictInitedDfd != null) {
        dictInitedDfd.resolve();
      }
      return this.sendMessage({
        type: 'history',
        history: storage.history
      });
    }
  };
  chrome.windows.onRemoved.addListener(function(wid) {
    var ref;
    if (((ref = dictWindowManager.w) != null ? ref.id : void 0) === wid) {
      dictWindowManager.w = null;
      dictWindowManager.tid = null;
      dictWindowManager.lastUrl = null;
      updateWindowDfd = null;
      injectContentDfd = null;
      return dictInitedDfd = null;
    }
  });
  return dictWindowManager;
});
