// Generated by CoffeeScript 1.10.0
require.config({
  baseUrl: "",
  paths: {
    "jquery": "bower_components/jquery/dist/jquery",
    "utils": "utils"
  },
  shim: {
    utils: {
      "exports": "utils"
    }
  }
});

require(["jquery", "utils", "background/setting", "background/ext", "background/dictwindow.js", "background/message.js"], function($, utils, setting, ext, dictWindow, message) {
  var onClickedContextMenu;
  onClickedContextMenu = function(info, tab) {
    if (info.selectionText) {
      return dictWindow.lookup(info.selectionText);
    }
  };
  chrome.browserAction.onClicked.addListener(function(tab) {
    var b;
    b = !setting.getValue('enableMinidict');
    setting.setValue('enableMinidict', b);
    return ext.setBrowserIcon(b);
  });
  setting.init().done(function(c) {
    return ext.setBrowserIcon(c.enableMinidict);
  });
  return chrome.contextMenus.create({
    title: "使用 FairyDict 查询 '%s'",
    contexts: ["selection"],
    onclick: onClickedContextMenu
  });
});
