// Generated by CoffeeScript 1.10.0
require.config({
  baseUrl: "",
  paths: {
    "jquery": "bower_components/jquery/dist/jquery",
    "utils": "utils"
  },
  shim: {
    utils: {
      "exports": "utils"
    }
  }
});

require(["jquery", "utils", "background/setting", "background/dictwindow.js", "background/message.js"], function($, utils, setting, dictWindow, message) {
  var onClickedContextMenu, setBrowserIcon;
  setBrowserIcon = function(enable) {
    var imgPath, title;
    title = '已打开鼠标取词功能';
    imgPath = 'images/dict-on24.png';
    if (!enable) {
      title = '已关闭鼠标取词功能';
      imgPath = 'images/dict-off24.png';
    }
    chrome.browserAction.setTitle({
      title: title
    });
    return chrome.browserAction.setIcon({
      path: imgPath
    });
  };
  onClickedContextMenu = function(info, tab) {
    if (info.selectionText) {
      return dictWindow.lookup(info.selectionText);
    }
  };
  chrome.browserAction.onClicked.addListener(function(tab) {
    var b;
    b = !setting.getValue('enableMinidict');
    setting.setValue('enableMinidict', b);
    return setBrowserIcon(b);
  });
  setting.init().done(function(c) {
    return setBrowserIcon(c.enableMinidict);
  });
  return chrome.contextMenus.create({
    title: "使用 FairyDict 查询 '%s'",
    contexts: ["selection"],
    onclick: onClickedContextMenu
  });
});
