// Generated by CoffeeScript 1.10.0
define(["jquery", "utils", "background/setting", "background/dict.js", "background/dictwindow.js"], function($, utils, setting, dict, dictWindow) {
  console.log("[message] init");
  return chrome.runtime.onMessage.addListener(function(request, sender, sendResponse) {
    var dictionary;
    if (request.type === 'getJson') {
      utils.getJson(request.url, request.data).then((function(res) {
        return sendResponse(res);
      }), sendResponse);
    } else if (request.type === 'postJson') {
      utils.postJson(request.url, request.data).then((function(res) {
        return sendResponse(res);
      }), sendResponse);
    } else if (request.type === 'look up') {
      if (request.means === 'mouse') {
        if (!setting.getValue('enableMinidict')) {
          return;
        }
      }
      dictWindow.lookup(request.text);
    } else if (request.type === 'query') {
      if (request.dictionary) {
        setting.setValue('dictionary', request.dictionary);
      }
      dictWindow.queryDict(request.text, request.dictionary, request.queryId);
    } else if (request.type === 'keySettings') {
      sendResponse({
        specialKeys: setting.getValue('specialKeys'),
        normalKey: setting.getValue('normalKey')
      });
    } else if (request.type === 'dictionary') {
      dictionary = setting.getValue('dictionary');
      sendResponse({
        allDicts: dict.allDicts,
        dictionary: dictionary
      });
    }
    return true;
  });
});
