// Generated by CoffeeScript 1.10.0
define(["jquery", "utils"], function($, utils) {
  var storage;
  storage = {
    maxLength: 100,
    history: [],
    init: function() {
      var dfd;
      dfd = $.Deferred();
      chrome.storage.sync.get('history', (function(_this) {
        return function(data) {
          _this.history = data.history || [];
          return dfd.resolve(data);
        };
      })(this));
      return dfd;
    },
    appendHistory: function(word) {
      if (this.history.length >= this.maxLength) {
        this.history.shift();
      }
      this.history.push(word);
      return chrome.storage.sync.set({
        history: this.history
      });
    }
  };
  return storage;
});
